// ------------------------------------------------------------------------------
// <auto-generated>
//     This file is generated by tool.
//     Runtime Version : 0.1.0
//  
// </auto-generated>
// ------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using Kae.StateMachine;
using Kae.DomainModel.Csharp.Framework;

namespace ProcessManagement
{
    partial class DomainClassRESBase
    {
        public string GetAssignerName()
        {
            // TODO : Let's write code!
            // Action Description on Model as a reference
            //  1 : SELECT ONE resourceAssigner RELATED BY SELF->RA[R6];
            //  2 : RETURN resourceAssigner.Name;

            var changedStates = new List<ChangedState>();
           // Generated from action description
            // Line : 1
            var resourceAssigner = this.LinkedR6();

            // Line : 2
            instanceRepository.SyncChangedStates(changedStates);
            return resourceAssigner.Attr_Name;


        }


    }
}
