// ------------------------------------------------------------------------------
// <auto-generated>
//     This file is generated by tool.
//     Runtime Version : 0.1.0
//  
// </auto-generated>
// ------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using Kae.StateMachine;
using Kae.DomainModel.Csharp.Framework;

namespace ProcessManagement
{
    partial class DomainClassRESStateMachine
    {
        protected void ActionFree()
        {
            // Action Description on Model as a reference.

            //  1 : SELECT one resourceAssigner RELATED BY SELF->RA[R6];
            //  2 : GENERATE RA2:'Resource Freed' TO resourceAssigner;

            // Line : 1
            var resourceAssigner = target.LinkedR6();

            // Line : 2
            DomainClassRAStateMachine.RA2_ResourceFreed.Create(receiver:resourceAssigner, sendNow:true);


        }

        protected void ActionBusy()
        {
            // Action Description on Model as a reference.



        }

    }
}
