// ------------------------------------------------------------------------------
// <auto-generated>
//     This file is generated by tool.
//     Runtime Version : 0.1.0
//  
// </auto-generated>
// ------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using Kae.StateMachine;
using Kae.DomainModel.Csharp.Framework;

namespace ProcessManagement
{
    partial class DomainClassPSBase
    {
        public void ExecuteCommand(string command)
        {
            // TODO : Let's write code!
            // Action Description on Model as a reference

            var changedStates = new List<ChangedState>();
           // Generated from action description

        
            instanceRepository.SyncChangedStates(changedStates);
        }


    }
}
